name: validating flutter execution

on:
  pull_request:
    paths:
      - 'mobile_app/**'

jobs:
  flutter-ci:
    name: Flutter Linting & Unit Testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile_app

    steps:
      - name: Download repository code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run unit & widget tests
        run: flutter test --coverage