name:  validating go execution 

on:
  pull_request:
    paths:
     - backend/**

jobs:
    
    repo-validation:
      name:  Installing ubuntu
      runs-on:  ubuntu-latest
      defaults:
        run:
          working-directory:  backend
      steps:
       - name:  Download repository code
         uses:  actions/checkout@v4
       - name: Installing go
         uses: actions/setup-go@v4
         with:
           go-version: '1.23'
           cache-dependency-path: backend/go.sum
       - name: Validating the syntax using linter
           uses: golangci/golangci-lint-action@v6
         with:
           working-directory: backend
       - name: Validating the code using go test
         run: |
           go test ./... -race -v -coverprofile=coverage.out
           go tool cover -func=coverage.out
           COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')

           if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
           echo "Coverage ($COVERAGE%) is below 80% threshold!"
           exit 1
           fi

         

